Objetivo: -   Calcule variaciones mensuales de volumen y precio

* Convertir data de raw a formato parquet
* guardar la data en interim
* escoger un producto en especifico para analizar y comenzar a armar las metricas

In [1]:
import pandas as pd
import numpy as np
import polars as pl
import pyarrow

* Obteniendo la ruta de los  archivos

In [ ]:
from pathlib import Path

BASE_DIR=Path().resolve()
DATA_PATH=BASE_DIR.parent / 'data/raw'

files = list(DATA_PATH.glob('*.xlsx'))
for f in files:
    print(f)

* funcion para leer un excel y pasarlo a polars

In [ ]:
def read_excel_polars(file_path: Path) -> pl.DataFrame:
    df_pd=pd.read_excel(file_path)
    df_pl=pl.from_pandas(df_pd)

    return df_pl

In [ ]:
dfs=[read_excel_polars(file) for file in files]
df_all=pl.concat(dfs, how='vertical_relaxed')

In [ ]:
output_path=BASE_DIR.parent / 'data/interim'
df_all.write_parquet(output_path / 'df_all.parquet')

* Analisis de data y seleccion de data
* esto con el fin de trabajar con un solo ejemplo
* un solo producto

In [2]:
from pathlib import Path

BASE_DIR=Path().resolve()
output_path=BASE_DIR.parent / 'data/interim'
df_final=pl.scan_parquet(output_path / 'df_all.parquet')

In [23]:
df_final.collect_schema()

Schema([('DÍA', Int64),
        ('MES', Int64),
        ('AÑO', Int64),
        ('DUA', Int64),
        ('SERIE', Int64),
        ('ADUANA', String),
        ('TIPO DOCUMENTO', String),
        ('RUC IMPORTADOR', Int64),
        ('IMPORTADOR', String),
        ('DIRECCIÓN', String),
        ('TELÉFONO', String),
        ('FAX', String),
        ('DEPARTAMENTO DE IMPORTADOR', String),
        ('PROVINCIA', String),
        ('DISTRITO', String),
        ('VÍA DE TRANSPORTE', String),
        ('BANCO', String),
        ('PAÍS DE ORIGEN', String),
        ('PAÍS DE ADQUISICIÓN', String),
        ('PUERTO DE EMBARQUE', String),
        ('PARTIDA ARANCELARIA', Int64),
        ('DESCRIPCIÓN ARANCELARIA', String),
        ('MERCANCÍA', String),
        ('DESCRIPCIÓN DE MERCANCÍA 1', String),
        ('DESCRIPCIÓN DE MERCANCÍA 2', String),
        ('DESCRIPCIÓN DE MERCANCÍA 3', String),
        ('DESCRIPCIÓN DE MERCANCÍA 4', String),
        ('PRODUCTO', String),
        ('MARCA', String),
        ('MODELO', String),
        ('CARACTERÍSTICAS', String),
        ('AÑO FABRICACIÓN', Float64),
        ('US$ FOB', Float64),
        ('US$ FLETE', Float64),
        ('US$ SEGURO', Float64),
        ('US$ CIF', Float64),
        ('ADVALOREM', Float64),
        ('IGV', Float64),
        ('IPM', Float64),
        ('PESO NETO', Float64),
        ('PESO BRUTO', Float64),
        ('CANTIDAD', Float64),
        ('UNIDAD DE MEDIDA', String),
        ('US$ CIF UNIT', Float64),
        ('CANTIDAD COMERCIAL', Float64),
        ('UNIDAD COMERCIAL', String),
        ('TIPO DE BULTO', String),
        ('CANTIDAD BULTO', Float64),
        ('ESTADO DE MERCANCIA', String),
        ('PROBABLE EMBARCADOR', String),
        ('AGENTE DE ADUANA', String),
        ('EMPRESA DE TRANSPORTE', String),
        ('ALMACEN', String),
        ('INCOTERM', String),
        ('MANIFIESTO DE CARGA', Int64),
        ('FECHA DE LLEGADA', Float64),
        ('US$ FOB UNIT', Float64),
        ('BILL OF LADING MASTER', String),
        ('BILL OF LADING', String),
        ('FECHA DE EMBARQUE', Float64),
        ('BUQUE', String),
        ('AGENTE DE CARGA EN DESTINO', String),
        ('FORMA DE PAGO', String),
        ('CANAL', String)])

In [ ]:
(
    df_final.group_by(pl.col('PARTIDA ARANCELARIA'))
    .agg(pl.col('US$ FOB').sum().alias('TOTAL_VALOR_FOB'))
    .sort('TOTAL_VALOR_FOB', descending=True)
    .collect()
).limit(20).to_pandas()

In [5]:
df_2710=df_final.filter(pl.col('PARTIDA ARANCELARIA') == 2710200012).collect()

El producto elegido esta asociado a la siguiente partida arancelaria
* Partida arancelaria 2710200012
* Descripcion arancelaria: Diesel B5, Con Un Contenido De Azufre Menor O Igual A 50 Ppm
* Producto: Diesel

Lo que se va calcular son las siguientes metricas
* Precio unitario mensual
* Volumen mensual
* Valor mensual

1. Construyes esto (nivel 1):

| periodo | precio | volumen |

In [3]:
def build_hs_monthly_base(
    df: pl.DataFrame,
    hs_code: str,
    hs_col: str = "hs_code",
    unit_col: str = "unidad_medida",
    value_col: str = "valor",
    quantity_col: str = "cantidad",
    day_col: str = "DIA",
    month_col: str = "MES",
    year_col: str = "AÑO",
) -> pl.DataFrame:
    return (
        df
        .filter(pl.col(hs_col) == hs_code)
        .filter(pl.col(unit_col).is_not_null())
        .with_columns([
            pl.col(day_col).cast(pl.Int32),
            pl.col(month_col).cast(pl.Int32),
            pl.col(year_col).cast(pl.Int32),
        ])
        .with_columns(
            pl.date(
                pl.col(year_col),
                pl.col(month_col),
                pl.col(day_col),
            ).alias("fecha")
        )
        .with_columns(
            pl.col("fecha").dt.truncate("1mo").alias("periodo")
        )
        .group_by(["periodo", hs_col, unit_col])
        .agg([
            pl.col(value_col).sum().alias("valor_total"),
            pl.col(quantity_col).sum().alias("volumen_total"),
        ])
        .with_columns(
            pl.when(pl.col("volumen_total") > 0)
            .then(pl.col("valor_total") / pl.col("volumen_total"))
            .otherwise(None)
            .alias("precio")
        )
        .select([
            "periodo",
            pl.col(hs_col).alias("hs_code"),
            pl.col(unit_col).alias("unidad_medida"),
            pl.col("volumen_total").alias("volumen"),
            "precio",
        ])
        .sort(["periodo", "unidad_medida"])
    )

In [10]:
df_2710=df_2710.with_columns(
    pl.col("PARTIDA ARANCELARIA").cast(str))

In [13]:
df_2710

shape: (436, 64)
┌─────┬─────┬──────┬──────┬───┬────────┬────────────────────────────┬───────────────┬─────────┐
│ DÍA ┆ MES ┆ AÑO  ┆ DUA  ┆ … ┆ BUQUE  ┆ AGENTE DE CARGA EN DESTINO ┆ FORMA DE PAGO ┆ CANAL   │
│ --- ┆ --- ┆ ---  ┆ ---  ┆   ┆ ---    ┆ ---                        ┆ ---           ┆ ---     │
│ i64 ┆ i64 ┆ i64  ┆ i64  ┆   ┆ str    ┆ str                        ┆ str           ┆ str     │
╞═════╪═════╪══════╪══════╪═══╪════════╪════════════════════════════╪═══════════════╪═════════╡
│ 23  ┆ 1   ┆ 2025 ┆ 88   ┆ … ┆ null   ┆ IAN TAYLOR PERU S.A.C      ┆ null          ┆ VERDE   │
│ 23  ┆ 1   ┆ 2025 ┆ 23   ┆ … ┆ null   ┆ null                       ┆ null          ┆ NARANJA │
│ 3   ┆ 1   ┆ 2025 ┆ 3302 ┆ … ┆ QUARTZ ┆ null                       ┆ PAGO DIFERIDO ┆ VERDE   │
│ 3   ┆ 1   ┆ 2025 ┆ 4    ┆ … ┆ null   ┆ IAN TAYLOR PERU S.A.C      ┆ PAGO DIFERIDO ┆ VERDE   │
│ 7   ┆ 1   ┆ 2025 ┆ 9373 ┆ … ┆ null   ┆ null                       ┆ null          ┆ VERDE   │
│ …   ┆ …   ┆ …    ┆ …    ┆ … ┆ …      ┆ …                          ┆ …             ┆ …       │
│ 23  ┆ 12  ┆ 2025 ┆ 1668 ┆ … ┆ null   ┆ null                       ┆ PAGO DIFERIDO ┆ VERDE   │
│ 29  ┆ 12  ┆ 2025 ┆ 1695 ┆ … ┆ null   ┆ null                       ┆ PAGO DIFERIDO ┆ VERDE   │
│ 3   ┆ 12  ┆ 2025 ┆ 570  ┆ … ┆ null   ┆ null                       ┆ PAGO DIFERIDO ┆ VERDE   │
│ 26  ┆ 12  ┆ 2025 ┆ 1683 ┆ … ┆ null   ┆ null                       ┆ PAGO DIFERIDO ┆ VERDE   │
│ 30  ┆ 12  ┆ 2025 ┆ 1698 ┆ … ┆ null   ┆ null                       ┆ PAGO DIFERIDO ┆ VERDE   │
└─────┴─────┴──────┴──────┴───┴────────┴────────────────────────────┴───────────────┴─────────┘

In [12]:
build_hs_monthly_base(
    df_2710,
    hs_code = "2710200012",
    hs_col = "PARTIDA ARANCELARIA",
    unit_col = "UNIDAD DE MEDIDA",
    value_col = "US$ FOB",
    quantity_col = "CANTIDAD",
    day_col = "DÍA",
    month_col = "MES",
    year_col = "AÑO",
)

shape: (0, 5)
┌─────────┬─────────┬───────────────┬─────────┬────────┐
│ periodo ┆ hs_code ┆ unidad_medida ┆ volumen ┆ precio │
│ ---     ┆ ---     ┆ ---           ┆ ---     ┆ ---    │
│ date    ┆ str     ┆ str           ┆ f64     ┆ f64    │
╞═════════╪═════════╪═══════════════╪═════════╪════════╡
└─────────┴─────────┴───────────────┴─────────┴────────┘